# Generated by Django 3.2.5 on 2022-06-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
