# Generated by Django 3.2.5 on 2022-06-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0002_alter_user_second_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Klasa',
                'verbose_name_plural': 'Klasa',
            },
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=2, unique=True)),
                ('punkty', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Oceny',
                'verbose_name_plural': 'Oceny',
            },
        ),
        migrations.CreateModel(
            name='Oryginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Dokumenty',
                'verbose_name_plural': 'Dokumenty',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
