# Generated by Django 3.2.5 on 2022-06-12 08:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0003_klasa_ocena_oryginal_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internat', models.BooleanField(default=False, verbose_name='Internat')),
                ('j_pol_egz', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='J.polski punkty egzamin')),
                ('mat_egz', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Matematyka punkty egzamin')),
                ('j_obcy_egz', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='J.obcy punkty egzamin')),
                ('sw_wyr', models.BooleanField(default=False, verbose_name='Świadectwo z wyróżnieniem')),
                ('konk_ponad_wyr', models.IntegerField(choices=[(0, 0), (5, 5), (7, 7), (10, 10)], default=0, verbose_name='Konkurs ponadwojewódzki')),
                ('konk_woj', models.IntegerField(choices=[(0, 0), (3, 3), (5, 5), (7, 7), (10, 10)], default=0, verbose_name='Konkurs wojewódzki')),
                ('konk_przedm', models.IntegerField(choices=[(0, 0), (3, 3), (4, 4), (10, 10)], default=0, verbose_name='Konkurs przedmiotowy')),
                ('konk_inne', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0, verbose_name='Konkursy inne ')),
                ('aktyw_spol', models.IntegerField(choices=[(0, 0), (3, 3)], default=0, verbose_name='Aktywność społeczna')),
                ('suma_pkt', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('biol_oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biol_oc', to='licznik.ocena', verbose_name='Biologia ocena')),
                ('clas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='licznik.klasa', verbose_name='Klasa')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='licznik.oryginal', verbose_name='Dokument')),
                ('inf_oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inf_oc', to='licznik.ocena', verbose_name='Informatyka ocena')),
                ('j_pol_oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='j_pol_oc', to='licznik.ocena', verbose_name='J.polski ocena')),
                ('mat_oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mat_oc', to='licznik.ocena', verbose_name='Matematyka ocena')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kandydat',
                'verbose_name_plural': 'Kandydat',
            },
        ),
    ]
